# -*- mode: ruby -*-
# vi: set ft=ruby
Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1604"
  config.vm.box_check_update = false

  config.vm.define "vagrant-ubuntu1604" do |host|
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-ubuntu-i3"
    vb.gui = true
    vb.cpus = 2
    vb.memory = "1024"

    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    vb.customize ['modifyvm', :id, '--accelerate3d', 'on']
    vb.customize ['modifyvm', :id, '--vram', '64']
    vb.customize ['modifyvm', :id, '--cpus', '2']
    vb.customize ['modifyvm', :id, '--bioslogofadein', 'off']
    vb.customize ['modifyvm', :id, '--bioslogofadeout', 'off']
    vb.customize ['modifyvm', :id, '--bioslogodisplaytime', '1000']
  end

  config.vm.provision "shell", privileged:false, inline: <<-SHELL
    sudo apt update -y
    sudo apt-get install -y i3 git vim zsh
    sudo apt install -y lightdm
    sudo systemctl enable lightdm
    sudo systemctl reboot
  SHELL
end
